version: '3'
services:
  app:
    build: ./app/
    depends_on:
      - server
    ports:
      - '51818:51818'

  server:
    build: ./server/
    command: ["sh", "-c", "sleep 30 && uvicorn main:app --host 0.0.0.0 --port 51717"]
    depends_on:
      - database
    ports:
      - '51717:51717'
      - "1717:1717"
    environment:
      - HTTP_PROXY=http://127.0.0.1:1717
      - HTTPS_PROXY=http://127.0.0.1:1717

  database:
    build: ./database/
    restart: always
    ports:
      - '52020:3306'

